# Generated by Django 4.2.7 on 2023-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField(max_length=10)),
                ('summary', models.TextField(max_length=1000)),
                ('degree', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('work_experience', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
            ],
        ),
    ]
